# Generated by Django 4.1.3 on 2023-02-20 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('review', 'Review'), ('issued', 'Issued'), ('closed', 'Closed')], default='review', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(choices=[('good_condition', 'Good Condition'), ('partly_damaged', 'Partly Damaged'), ('damaged', 'Damaged')], default='good_condition', max_length=30, verbose_name='Condition')),
                ('line_one', models.CharField(max_length=120, verbose_name='Item name')),
                ('line_one_order', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('line_one_issue', models.PositiveIntegerField(default=0, verbose_name='Issue Qty')),
                ('slug', models.SlugField(max_length=120)),
                ('line_two', models.CharField(blank=True, max_length=120, null=True, verbose_name='Extra Item One')),
                ('line_two_order', models.PositiveIntegerField(default=0, verbose_name='Req Qty')),
                ('line_two_issue', models.PositiveIntegerField(default=0, verbose_name='Issue Qty 1')),
                ('line_three', models.CharField(blank=True, max_length=120, null=True, verbose_name='Extra Item Two')),
                ('line_three_order', models.PositiveIntegerField(default=0, verbose_name='Req Qty')),
                ('line_three_issue', models.PositiveIntegerField(default=0, verbose_name='Issue Qty 2')),
                ('line_four', models.CharField(blank=True, max_length=120, null=True, verbose_name='Extra Item three')),
                ('line_four_order', models.PositiveIntegerField(default=0, verbose_name='Req Qty')),
                ('line_four_issue', models.PositiveIntegerField(default=0, verbose_name='Issue Qty 3')),
                ('request_message', models.TextField(blank=True, null=True, verbose_name='Request Comment')),
                ('issue_remark', models.TextField(blank=True, null=True, verbose_name='Issue Remarks')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True, verbose_name='System Trace Audit No.')),
                ('request_at', models.DateTimeField(auto_now_add=True, verbose_name='Request Time')),
                ('issue_at', models.DateTimeField(blank=True, null=True, verbose_name='Issue Time')),
                ('receive_at', models.DateTimeField(blank=True, null=True, verbose_name='Receipt Time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='general_settings.inventory', verbose_name='Category')),
                ('issue_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuebranch', to='general_settings.branch', verbose_name='Issue Branch')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_by', to=settings.AUTH_USER_MODEL, verbose_name='Issuer')),
                ('request_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestbranch', to='general_settings.branch', verbose_name='Request Branch')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_by', to=settings.AUTH_USER_MODEL, verbose_name='Issuer')),
            ],
            options={
                'verbose_name': 'All requests',
                'verbose_name_plural': 'All requests',
                'ordering': ['-request_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionClosed',
            fields=[
            ],
            options={
                'verbose_name': 'Closed Requests',
                'verbose_name_plural': 'Closed Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventoryrequest',),
        ),
        migrations.CreateModel(
            name='RequisitionIssued',
            fields=[
            ],
            options={
                'verbose_name': 'Issued Requests',
                'verbose_name_plural': 'Issued Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventoryrequest',),
        ),
        migrations.CreateModel(
            name='RequisitionReview',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Requests',
                'verbose_name_plural': 'Pending Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventoryrequest',),
        ),
    ]
