# Generated by Django 4.1.3 on 2023-02-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_grading_marks10_alter_grading_marks6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='criteria10',
            field=models.CharField(default='Criteria 10', max_length=100, verbose_name='Criteria 10'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='criteria6',
            field=models.CharField(default='Criteria 6', max_length=100, verbose_name='Criteria 6'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='criteria7',
            field=models.CharField(default='Criteria 7', max_length=100, verbose_name='Criteria 7'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='criteria8',
            field=models.CharField(default='Criteria 8', max_length=100, verbose_name='Criteria 8'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='criteria9',
            field=models.CharField(default='Criteria 9', max_length=100, verbose_name='Criteria 9'),
        ),
    ]
