# Generated by Django 4.1.3 on 2023-02-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_grading_criteria10_alter_grading_criteria6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='criteria10',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='criteria7',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='criteria8',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='criteria9',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='marks10',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='marks7',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='marks8',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='marks9',
        ),
    ]
