# Generated by Django 4.1.3 on 2023-02-22 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_alter_parameters_criteria1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
