# Generated by Django 4.1.3 on 2023-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_alter_grading_marks1_alter_grading_marks2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='states',
            field=models.CharField(choices=[('accept', 'Approve Vendor'), ('reject', 'Reject Vendor')], default='accept', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='justification',
            field=models.CharField(choices=[('low_score', 'Low Score or blacklist zone'), ('shortlist_satisfied', 'Cut-off already satisfied'), ('misconduct', 'Applicant misconduct prior or after application'), ('misrepresentation', 'Applicant misrepresentation of identity'), ('badhistory', 'Recent finding about vendor against our policies')], max_length=60, verbose_name='Justification (**if Rejected)'),
        ),
    ]
