# Generated by Django 4.1.3 on 2023-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_application_states_alter_application_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='states',
            field=models.CharField(choices=[('accept', 'Approve Vendor'), ('reject', 'Reject Vendor')], default='accept', max_length=20, verbose_name='State'),
        ),
    ]
