# Generated by Django 4.1.3 on 2023-02-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_alter_application_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='states',
        ),
        migrations.AlterField(
            model_name='panelist',
            name='name',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Meeting Link'),
        ),
    ]
