# Generated by Django 4.1.3 on 2023-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_panelist_meeting_link_alter_panelist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelist',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='application',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Meeting Link'),
        ),
    ]
