# Generated by Django 4.1.3 on 2023-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_alter_application_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Meeting Link'),
        ),
    ]
