# Generated by Django 4.1.3 on 2023-02-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0018_alter_application_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Reminder Count'),
        ),
    ]
